### ISSUE TITLE
Mocha 8.2.1 started causing an error for json-file-reporter

### ISSUE THREAD

**Issue by NazarYermolenko** [mocha-community/json-file-reporter#47]
The following error message started appearing after updating Mocha from 8.1.3 to 8.2.1

`/home/newfire/Desktop/work/qa-ui/node_modules/@mochajs/json-file-reporter/src/index.js:75
    fullTitle: test.fullTitle(),
                    ^
TypeError: test.fullTitle is not a function
    at clean (/home/newfire/Desktop/work/qa-ui/node_modules/@mochajs/json-file-reporter/src/index.js:75:21)
    at Array.map (<anonymous>)
    at ParallelBufferedRunner.<anonymous> (/home/newfire/Desktop/work/qa-ui/node_modules/@mochajs/json-file-reporter/src/index.js:48:26)
    at Object.onceWrapper (events.js:420:28)`

**Comment by munierujp** [comment]
@NazarYermolenko Sorry for the delay in replying.
In my environment, that problem did not occur.
Could you show me the repository or source codes when the problem is reproducible?

**Comment by NazarYermolenko** [comment]
The issue appears when all tests failing... 
```
/home/newfire/Desktop/work/qa-api/node_modules/@mochajs/json-file-reporter/src/index.js:75
    fullTitle: test.fullTitle(),
```

**Comment by NazarYermolenko** [comment]
Or when setup hook failing, I mean if the test has before the hook and the hook fails, the following error message appears
